config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show,:new,:create,:edit,:update]

  resources :sessions, only: [:new,:create] do
    delete :destroy, on: :collection
  end

  resources :comments, only: [:destroy]

  resources :shops do
    resources :comments, only: [:create]
  end

  resources :beans do
    resources :comments, only: [:create]
  end

  resources :recipes do
    resources :comments, only: [:create]
  end

  resources :shops, only: [] do
    resources :bean_shops, only: [:create]
  end

  resources :beans, only: [] do
    resources :bean_likes, only: [:create,:destroy]
  end

  resources :recipes, only: [] do
    resources :recipe_likes, only: [:create,:destroy]
  end

  resources :shops, only: [] do
    resources :shop_likes, only: [:create,:destroy]
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/:provider/callback" => "callbacks#index"

  root 'home#index'

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Geocoder
  geocoded_by :address
  after_validation :geocode

  # Carrierwave
  mount_uploader :cafeimg, CafeimgUploader

  belongs_to :user
  has_many :comments, as: :commentable

  #beans
  has_many :bean_shop, dependent: :destroy
  has_many :beans, through: :bean_shop

  #likes
  has_many :shop_likes, dependent: :destroy
  has_many :users, through: :shop_likes

  validates :name, presence: true
  validates :phone_number, presence: true

  def shop_like_for(user)
    shop_likes.find_by_user_id(user)
  end

  def self.search(search)
    where("name ILIKE ? OR website ILIKE ? OR address ILIKE ?", "%#{search}%","%#{search}%","%#{search}%")
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_shop, only: [:show,:destroy,:update,:edit]

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new shop_params
    @shop.user_id = current_user.id
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def index
    @shops = Shop.order("name").page(params[:page]).per(6)
    if params[:search]
    @shops = Shop.search(params[:search]).order("name").page(params[:page]).per(6)
    else
    @shops = Shop.all.order('name').page(params[:page]).per(6)
    end
    respond_to do |format|
      format.html
      format.js {render :shop_search}
    end
  end

  def show
    @bean = @shop.beans
    @comment = Comment.new
    @commentable = @shop
    @shop_like = @shop.shop_like_for(current_user)
  end

  def edit
    can_authorize(:edit,@shop)
  end

  def update
    can_authorize(:update,@shop)
    if @shop.update shop_params
      redirect_to shop_path(@shop), alert: "Updated"
    else
      flahs[:alert] = "Failed to update"
      render :edit
    end
  end

  def destroy
    can_authorize(:destroy,@shop)
    @shop.destroy
  end

  private

  def shop_params
    shop_params = params.require(:shop).permit(:phone_number,:name,:address,:website,:user_id,:cafeimg,:slug,:bean_id)
  end

  def find_shop
    @shop = Shop.friendly.find params[:id]
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= simple_form_for @shop do |f| %>
  <div class="well">
    <%= f.input :name, class: "form-input"%>
    <%= f.input :phone_number %>
    <%= f.input :address %>
    <%= f.input :website %>
    <%= f.input :cafeimg, as: :file %>
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

<!-- <%= simple_form_for @shop do |f| %>
<div class="container-form">
  <div class="group">
    <%= f.input :name %>
    <span class="highlight"></span>
    <span class="bar"></span>
    <label>Name</label>
  </div>

  <div class="group">
    <input type="text" required>
    <span class="highlight"></span>
    <span class="bar"></span>
    <label>Email</label>
  </div>
</div>
<% end %> -->

app/views/shops/_shop_search.html.erb
<div class="col-lg-4 bean-index">
  <div class="bean-index-self-img hvr-grow" alt="Fjords">
    <%= link_to image_tag(f.cafeimg_url(:xlarge).to_s),shop_path(f) %>
  </div>
    <div class="desc">
      <h4><%= link_to f.name, shop_path(f), class: "bean-name" %></h4>
      <p>Address: <%= f.address %> </p>
      <p>Website: <%= f.website %> </p>
      <p>Phone number: <%= f.phone_number %> </p>
    </div>
</div>

app/views/shops/edit.html.erb
<h1>Edit Shop</h1>

<%= render "form" %>

app/views/shops/index.html.erb
<div class="wrapper">
<!-- Header -->
<div class="cotainer" id="cafe-index"></div>
<!-- Header end -->

  <!-- search -->
  <div class="search">
    <%= form_tag(shops_path, :method => "get", id: "search", remote: true) do %>
    <div class="search-text">
      <%= text_field_tag :search, params[:search], placeholder: "Search Cafe(Type and press Enter)" %>
    </div>
    <% end %>
  </div>
  <!-- end of search -->

  <div class="cotainer" id="bean-index-outer">
    <div class="row">
      <div id="answers">
      <% @shops.each do |f| %>
        <%= render "shop_search", f: f %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class='text-center'>
  <%= paginate @shops, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= simple_form_for @shop do |f| %>
  <div class="well">
    <%= f.input :name %>
    <%= f.input :phone_number %>
    <%= f.input :address %>
    <%= f.input :website %>
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/shops/shop_search.js.erb
$("#answers").html("<%= raw (@shops.map {|f| j(render 'shop_search', f: f) }.join('')) %>");

app/views/shops/show.html.erb
<%= render "/layouts/google" %>
<div class="container">
<h2><%= @shop.name %></h2>
<br>
<%= image_tag @shop.cafeimg_url(:xlarge).to_s %>
<br>
<!-- likes -->
<% if @shop_like.present? && @shop_like.persisted? %>
  <%= link_to fa_icon("heart", base: "square-o", class: "fa-2x"), shop_shop_like_path(@shop, @shop_like), method: :delete %>
<% else %>
  <%= link_to fa_icon("heart-o", base: "square-o", class: "fa-2x"),shop_shop_likes_path(@shop), method: :post %>
<% end %>

<!-- edit/delete -->
<% if can? :edit, @shop %>
  <%= link_to "Edit", edit_shop_path(@shop) %>
<% end %>
<% if can? :delete, @shop %>
  <%= link_to "Delete", shop_path(@shop), method: :delete %>
<% end %>
<br>
<hr>
<p>Name:<%= @shop.name %></p>
<br>
<p>Address:<%= @shop.address %></p>
<br>
<p>Webiste:<%= @shop.website %></p>
<br>
<p>Phone Number:<%= @shop.phone_number %></p>
<hr>
<h3>Brewing Now:</h3>
<% @bean.each do |f| %>
  <%= link_to image_tag(f.beanimg_url(:thumb)), bean_path(f) %>
<% end %>
<hr>


<% if @shop.longitude && @shop.latitude %>
<div style='width: 500px;'>
  <div id="map" style='width: 500px; height: 350px;'></div>
</div>
<% end %>
<script>
 handler = Gmaps.build('Google');
 handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers([
      {
       "lat": <%= @shop.latitude %>,
       "lng": <%= @shop.longitude %>,
       "picture": {
         "url": "http://orig13.deviantart.net/4351/f/2010/178/f/6/free_jake_icon_by_picklecheesepie.gif",
         "width":  50,
         "height": 50
       },
     }
   ]);
   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();
 });

 </script>

 <%= render "comments/form" %>
 <%= render "comments/show" %>
</div>