config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show,:new,:create,:edit,:update]

  resources :sessions, only: [:new,:create] do
    delete :destroy, on: :collection
  end

  resources :comments, only: [:destroy]

  resources :shops do
    resources :comments, only: [:create]
  end

  resources :beans do
    resources :comments, only: [:create]
  end

  resources :recipes do
    resources :comments, only: [:create]
  end

  resources :shops, only: [] do
    resources :bean_shops, only: [:create]
  end

  resources :beans, only: [] do
    resources :bean_likes, only: [:create,:destroy]
  end

  resources :recipes, only: [] do
    resources :recipe_likes, only: [:create,:destroy]
  end

  resources :shops, only: [] do
    resources :shop_likes, only: [:create,:destroy]
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/:provider/callback" => "callbacks#index"

  root 'home#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Carrierwave
  mount_uploader :recipeimg, RecipeimgUploader

  belongs_to :user
  has_many :comments, as: :commentable

  # likes
  has_many :recipe_likes, dependent: :destroy
  has_many :users, through: :recipe_likes

  validates :name, presence: true
  validates :grind, presence: true

  def recipe_like_for(user)
    recipe_likes.find_by_user_id(user)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_recipe, only: [:show,:destroy,:edit,:update]

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new recipe_params
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, alert: "Delicious"
    else
      flash[:alert] = "Failed to create"
      render :new
    end
  end

  def index
    @recipes = Recipe.order("name").page(params[:page]).per(6)
    if params[:search]
    @recipes = Recipe.search(params[:search]).order("name").page(params[:page]).per(6)
    else
    @recipes = Recipe.all.order('name').page(params[:page]).per(6)
    end
  end

  def show
    @commentable = @recipe
    @comment = Comment.new
    @recipe_like = @recipe.recipe_like_for(current_user)
  end

  def edit
    can_authorize(:edit,@recipe)
  end

  def update
    can_authorize(:update,@recipe)
    if @recipe.update recipe_params
      redirect_to recipe_path(@recipe), alert: "Super Delicious"
    else
      flash[:alert] = "Could not update"
      render :edit
    end
  end

  def destroy
    can_authorize(:destroy,@recipe)
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    recipe_params = params.require(:recipe).permit(:name,:region,:roaster,:producer,:method,:rating,:notes,:grind,:private,:user_id,:recipeimg,:slug,:sweet,:fruity,:bitter,:chocolate)
  end

  def find_recipe
    @recipe = Recipe.friendly.find params[:id]
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f| %>
  <div class="well">
    <%= f.input :name %>
    <%= f.input :bean_name %>
    <%= f.input :method %>
    <%= f.input :rating %>
    <%= f.input :notes %>
    <%= f.input :grind %>
    <%= f.input :private %>
    <%= f.input :recipeimg, as: :file %>
    <%= f.input :sweet, collection: 0..10  %>
    <%= f.input :fruity, collection: 0..10  %>
    <%= f.input :bitter, collection: 0..10  %>
    <%= f.input :chocolate, collection: 0..10  %>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Update one cup at a time</h1>

<%= render "form" %>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <div class="recipe-button">
        <%= link_to "New Recipe", new_recipe_path %>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="recipe-button">
        <%= link_to "My Recipes", new_recipe_path %>
      </div>
    </div>
  </div>
</div>

  <div class="cotainer" id="bean-index-outer">
    <div class="row">
      <% @recipes.each do |f| %>
        <div class="col-lg-4 bean-index">
          <div class="bean-index-self-img hvr-grow" alt="Fjords">
            <%= link_to image_tag(f.recipeimg_url(:thumb)), recipe_path(f) %>
          </div>
            <div class="desc">
              <h4><%= link_to f.name, recipe_path(f), class: "bean-name" %></h4>
              <p>Method: <%= f.method %></p>
              <p>Rating: <%= f.rating %></p>
              <p>Rating: <%= f.grind %></p>
            </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class='text-center'>
    <%= paginate @recipes, :theme => 'twitter-bootstrap-3' %>
  </div>

app/views/recipes/new.html.erb
<h1>One Cup at a time</h1>

<%= render "form" %>

app/views/recipes/show.html.erb
<div class="container">
<h2><%= @recipe.name %></h2>
<%= image_tag @recipe.recipeimg_url.to_s %>
<br>
<!-- likes -->
<% if @recipe_like.present? && @recipe_like.persisted? %>
  <%= link_to fa_icon("heart", base: "square-o", class: "fa-2x"), recipe_recipe_like_path(@recipe, @recipe_like), method: :delete %>
<% else %>
  <%= link_to fa_icon("heart-o", base: "square-o", class: "fa-2x"), recipe_recipe_likes_path(@recipe), method: :post %>
<% end %>

<!-- edit/delete -->
<% if can? :edit, @recipe %>
  <%= link_to "Edit", edit_recipe_path(@recipe) %>
<% end %>
<% if can? :delete, @recipe %>
  <%= link_to "Delete", recipe_path(@recipe), method: :delete %>
<% end %>
<hr>
<p>Name:<%= @recipe.name %></p>
<p>Method:<%= @recipe.method %></p>
<p>Rating:<%= @recipe.rating %></p>
<p>Notes:<%= @recipe.notes %></p>
<p>Grind Type:<%= @recipe.grind %></p>
<hr>
<%= render "comments/form" %>
<%= render "comments/show" %>
</div>