config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show,:new,:create,:edit,:update]

  resources :sessions, only: [:new,:create] do
    delete :destroy, on: :collection
  end

  resources :comments, only: [:destroy]

  resources :shops do
    resources :comments, only: [:create]
  end

  resources :beans do
    resources :comments, only: [:create]
  end

  resources :recipes do
    resources :comments, only: [:create]
  end

  resources :shops, only: [] do
    resources :bean_shops, only: [:create]
  end

  resources :beans, only: [] do
    resources :bean_likes, only: [:create,:destroy]
  end

  resources :recipes, only: [] do
    resources :recipe_likes, only: [:create,:destroy]
  end

  resources :shops, only: [] do
    resources :shop_likes, only: [:create,:destroy]
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/:provider/callback" => "callbacks#index"

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :first_name, use: [:slugged, :history]

  # Carrierwave
  mount_uploader :avatar, AvatarUploader

  # bcrypt
  has_secure_password

  has_many :shops, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :beans, dependent: :destroy
  has_many :comments, dependent: :destroy

  #likes
  has_many :bean_likes, dependent: :destroy
  has_many :like_beans, through: :bean_likes, source: :bean

  has_many :recipe_likes, dependent: :destroy
  has_many :like_recipes, through: :recipe_likes, source: :recipe

  has_many :shop_likes, dependent: :destroy
  has_many :like_shops, through: :shop_likes, source: :shop

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
            unless: :from_omniauth?
  validates :password, presence: true, length: { minimum: 5 }

  # Twitter raw-data
  serialize :twitter_raw_data

  def self.find_from_omniauth(omniauth_data)
  User.where(provider: omniauth_data["provider"],
             uid:      omniauth_data["uid"]).first
  end

  def self.create_from_omniauth(omniauth_data)
  full_name = omniauth_data["info"]["name"].split
  User.create(uid:                      omniauth_data["uid"],
              provider:                 omniauth_data["provider"],
              first_name:               full_name[0],
              last_name:                full_name[1],
              twitter_consumer_token:   omniauth_data["credentials"]["token"],
              twitter_consumer_secret:  omniauth_data["credentials"]["secret"],
              twitter_raw_data:         omniauth_data,
              password:                 SecureRandom.hex(16)
              )
            end

  private

  def from_omniauth?
    uid.present? && provider.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update user_params
      redirect_to user_path(@user), alert: "Updated"
    else
      render :edit
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, alert: "Account Created"
    else
      flash[:alert] = "Failed to create an account"
      render :new
    end
  end

  def show
   @user = User.friendly.find params[:id]
   @beans = current_user.like_beans
   @shops = current_user.like_shops
   @recipes = current_user.like_recipes

   if current_user.like_beans.count > 1
   @counter = 0
   @taste = { sweet: 0, fruity: 0, bitter: 0, chocolate: 0}
   @beans.each do |bean|
     @taste[:sweet] += bean.sweet
     @taste[:fruity] += bean.fruity
     @taste[:bitter] += bean.bitter
     @taste[:chocolate] += bean.chocolate
     @counter += 1
   end

   @recipes.each do |bean|
     @taste[:sweet] += bean.sweet
     @taste[:fruity] += bean.fruity
     @taste[:bitter] += bean.bitter
     @taste[:chocolate] += bean.chocolate
     @counter += 1
   end

   @taste.each do |key,value|
     @taste[key] = value / @counter
   end

   @sweet = (@taste[:sweet] * 10).to_s + "%"
   @fruity = (@taste[:fruity] * 10).to_s + "%"
   @chocolate = (@taste[:chocolate] * 10).to_s + "%"
   @bitter = (@taste[:bitter] * 10).to_s + "%"
   # /====================================
       # Recommendation algorithm
   # ====================================/
   # putting all the taste values from use to array
   @rec_taste = Array.new
   @taste.each_value {|value| @rec_taste.push(value)}

   # putting all the taste values from beans to a hash with key bean_id and vlaue
   @beans_all = Bean.where("id NOT IN (?)", current_user.like_beans.pluck(:bean_id))
   @rec_bean = Hash.new

   @beans_all.each do |bean|
     @rec_bean[bean.id] = [bean.sweet, bean.fruity, bean.bitter, bean.chocolate]
   end

   @rec_bean.each do |key,value|
     print @rec_taste[0]
     print value[0]
     @rec_bean[key] = Math.sqrt(((@rec_taste[0]-value[0])**2)+((@rec_taste[1]-value[1])**2)+((@rec_taste[2]-value[2])**2)+((@rec_taste[3]-value[3])**2) )
   end

   @rec_bean_num = Array.new
   @rec_bean.each do |key,value|
     if value < 5
       @rec_bean_num.push(key)
     end
   end

   @rec_bean_final = Array.new
   @rec_bean_num.each do |f|
     @rec_bean_final.push(Bean.find(f))
   end

  #  # Recipes
  #
  #  # putting all the taste values from use to array
  #  @rec_taste = Array.new
  #  @taste.each_value {|value| @rec_taste.push(value)}
  #
  #  # putting all the taste values from beans to a hash with key bean_id and vlaue
  #  @recipes_all = Recipe.where("id NOT IN (?)", current_user.like_recipes.pluck(:recipe_id))
  #  @rec_recipe = Hash.new
  #
  #  @recipes_all.each do |recipe|
  #    @rec_recipe[recipe.id] = [recipe.sweet, recipe.fruity, recipe.bitter, recipe.chocolate]
  #  end
  #
  #  @rec_recipe.each do |key,value|
  #    print @rec_taste[0]
  #    print value[0]
  #    @rec_recipe[key] = Math.sqrt(((@rec_taste[0]-value[0])**2)+((@rec_taste[1]-value[1])**2)+((@rec_taste[2]-value[2])**2)+((@rec_taste[3]-value[3])**2) )
  #  end
  #
  #  @rec_recipe_num = Array.new
  #  @rec_recipe.each do |key,value|
  #    if value < 5
  #      @rec_recipe_num.push(key)
  #    end
  #  end
  #
  #  @rec_recipe_final = Array.new
  #  @rec_recipe_num.each do |f|
  #    @rec_recipe_final.push(Recipe.find(f))
  #  end


    # @user = User.friendly.find params[:id]
    # @beans = current_user.like_beans
    # @beanss = current_user.like_beans
    # @shops = current_user.like_shops
    # @recipes = current_user.like_recipes
    # @recommended_beans = BeanRecommendationEngine.new(current_user).recommended_beans
    taste_graph!
    end
  end

  private

  def user_params
    user_params = params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation,:avatar,:slug)
  end

  def taste_graph!
    @counter = 0
    @taste = { sweet: 0, fruity: 0, bitter: 0, chocolate: 0}
    @beans.each do |bean|
      @taste[:sweet] += bean.sweet
      @taste[:fruity] += bean.fruity
      @taste[:bitter] += bean.bitter
      @taste[:chocolate] += bean.chocolate
      @counter += 1
    end

    @recipes.each do |bean|
      @taste[:sweet] += bean.sweet
      @taste[:fruity] += bean.fruity
      @taste[:bitter] += bean.bitter
      @taste[:chocolate] += bean.chocolate
      @counter += 1
    end

    @taste.each do |key,value|
      @taste[key] = value / @counter
    end

    @sweet = (@taste[:sweet] * 10).to_s + "%"
    @fruity = (@taste[:fruity] * 10).to_s + "%"
    @chocolate = (@taste[:chocolate] * 10).to_s + "%"
    @bitter = (@taste[:bitter] * 10).to_s + "%"

  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :avatar, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>
<%= render "form" %>

app/views/users/new.html.erb
<div class="container sign_up">
  <h1>Sign Up</h1>
  <%= render "form" %>
</div>

app/views/users/show.html.erb
<!-- User Info -->
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <div class="bean-index-self-img" alt="Fjords">
        <%= image_tag current_user.avatar_url(:thumb).to_s %>
      </div>
    </div>
    <hr>
    <div class="col-lg-6">
      <div class="user-info">
        <%= @user.first_name %>
        <hr>
        <%= @user.last_name %>
        <hr>
        <%= @user.email %>
        <hr>
        <%= link_to "Edit Profile", edit_user_path(@user) %>
      </div>
    </div>
  </div>
</div>
<!-- User Info End -->

<!-- Likes -->
<div class="container" id="user-show-content">
  <div class="row">
    <h2>Liked Beans</h2>
    <% @beans.each do |f| %>
      <div class="col-lg-4 col-md-12">
        <%= f.name %>
        <%= link_to image_tag(f.beanimg_url(:thumb).to_s), bean_path(f) %>
      </div>
    <% end %>
  </div>
</div>
<hr>

<div class="container" id="user-show-content">
  <div class="row">
    <h2>Liked Shops</h2>
    <% @shops.each do |f| %>
      <div class="col-lg-4 col-md-12">
        <%= f.name %>
        <%= link_to image_tag(f.cafeimg_url(:thumb).to_s), shop_path(f) %>
      </div>
    <% end %>
  </div>
</div>
<hr>


<div class="container" id="user-show-content">
  <div class="row">
    <h2>Liked Recipes</h2>
    <% @recipes.each do |f| %>
      <div class="col-lg-4 col-md-12">
        <%= f.name %>
        <%= link_to image_tag(f.recipeimg_url(:thumb).to_s), recipe_path(f) %>
      </div>
    <% end %>
  </div>
</div>
<hr>
<!-- Likes End -->

<!--  Recommendatoin Start -->
<div class="container">
  <% if @rec_bean_final != nil %>
    <h2>Recommendation</h2>
	  <div class="row">
		  <div class="col-md-4 col-sm-12">
        <h3>Taste bar <span class="semi-bold"></span></h3>
        <br>
        <div class="col-md-11">
          <p>Sweet</p>
          <div class="progress">
            <div data-percentage="0%" style="width: <%= @sweet %>;" class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <p>Fruity</p>
          <div class="progress">
            <div data-percentage="0%" style="width: <%= @fruity %>;"  class="progress-bar progress-bar-info" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <p>Bitter</p>
          <div class="progress">
            <div data-percentage="0%" style="width: <%= @bitter %>;" class="progress-bar progress-bar-warning" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <p>Chocolate</p>
          <div class="progress">
            <div data-percentage="0%" style="width: <%= @chocolate %>;" class="progress-bar progress-bar-danger" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
	</div>
<hr>
</div>
<% else %>
  <div class="container">
    <h2>Recommendation</h2>
	  <div class="row">
		  <div class="col-md-4">
        <h3>Taste bar <span class="semi-bold"></span></h3>
        <br>
        <div class="col-md-12">
          <p> There is no beeans you have liked to generate a graph</p>
        </div>
      </div>
    </div>
	</div>
  <hr>
</div>
</div>
<% end %>

<% if @rec_bean_final != nil %>
  <!-- <%= @taste %> -->
    <div class="container" id="user-show-content">
      <div class="row">
        <h2>Check out these beans</h2>
        <% @rec_bean_final.each do |f| %>
          <div class="col-lg-4 col-md-12">
            <%= link_to f.name, bean_path(f) %>
            <%= link_to image_tag(f.beanimg_url(:thumb)), bean_path(f) %>
          </div>
        <% end %>
      </div>
    </div>
<% end %>
<!-- Recommendation End -->