config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show,:new,:create,:edit,:update]

  resources :sessions, only: [:new,:create] do
    delete :destroy, on: :collection
  end

  resources :comments, only: [:destroy]

  resources :shops do
    resources :comments, only: [:create]
  end

  resources :beans do
    resources :comments, only: [:create]
  end

  resources :recipes do
    resources :comments, only: [:create]
  end

  resources :shops, only: [] do
    resources :bean_shops, only: [:create]
  end

  resources :beans, only: [] do
    resources :bean_likes, only: [:create,:destroy]
  end

  resources :recipes, only: [] do
    resources :recipe_likes, only: [:create,:destroy]
  end

  resources :shops, only: [] do
    resources :shop_likes, only: [:create,:destroy]
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/:provider/callback" => "callbacks#index"

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

    can :manage, Bean do |bean|
      bean.user == user
    end

    can :manage, Comment do |comment|
      comment.user == user
    end

    can :manage, Shop do |shop|
      shop.user == user
    end

    can :manage, Recipe do |recipe|
      recipe.user == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/bean.rb
class Bean < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Carrierwave
  mount_uploader :beanimg, BeanimgUploader

  #beans
  has_many :bean_shop, dependent: :destroy
  has_many :shops, through: :bean_shop

  belongs_to :user
  has_many :comments, as: :commentable

  validates :name, presence: true
  validates :region, presence: true

  # likes
  has_many :bean_likes, dependent: :destroy
  has_many :users, through: :bean_likes

  def bean_like_for(user)
    bean_likes.find_by_user_id(user)
  end

  def self.search(search)
    where("name ILIKE ? OR roast ILIKE ? OR region ILIKE ?", "%#{search}%","%#{search}%","%#{search}%")
  end
end

app/models/bean_like.rb
class BeanLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :bean
end

app/models/bean_shop.rb
class BeanShop < ActiveRecord::Base
  belongs_to :bean
  belongs_to :shop
end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :region, presence: true
  validates :method, presence: true
  validates :rating, presence: true
  validates :bean_name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :body, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Carrierwave
  mount_uploader :recipeimg, RecipeimgUploader

  belongs_to :user
  has_many :comments, as: :commentable

  # likes
  has_many :recipe_likes, dependent: :destroy
  has_many :users, through: :recipe_likes

  validates :name, presence: true
  validates :grind, presence: true

  def recipe_like_for(user)
    recipe_likes.find_by_user_id(user)
  end

end

app/models/recipe_like.rb
class RecipeLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Geocoder
  geocoded_by :address
  after_validation :geocode

  # Carrierwave
  mount_uploader :cafeimg, CafeimgUploader

  belongs_to :user
  has_many :comments, as: :commentable

  #beans
  has_many :bean_shop, dependent: :destroy
  has_many :beans, through: :bean_shop

  #likes
  has_many :shop_likes, dependent: :destroy
  has_many :users, through: :shop_likes

  validates :name, presence: true
  validates :phone_number, presence: true

  def shop_like_for(user)
    shop_likes.find_by_user_id(user)
  end

  def self.search(search)
    where("name ILIKE ? OR website ILIKE ? OR address ILIKE ?", "%#{search}%","%#{search}%","%#{search}%")
  end
end

app/models/shop_like.rb
class ShopLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop
end

app/models/taste.rb
class Taste < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # friendly_id
  extend FriendlyId
  friendly_id :first_name, use: [:slugged, :history]

  # Carrierwave
  mount_uploader :avatar, AvatarUploader

  # bcrypt
  has_secure_password

  has_many :shops, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :beans, dependent: :destroy
  has_many :comments, dependent: :destroy

  #likes
  has_many :bean_likes, dependent: :destroy
  has_many :like_beans, through: :bean_likes, source: :bean

  has_many :recipe_likes, dependent: :destroy
  has_many :like_recipes, through: :recipe_likes, source: :recipe

  has_many :shop_likes, dependent: :destroy
  has_many :like_shops, through: :shop_likes, source: :shop

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
            unless: :from_omniauth?
  validates :password, presence: true, length: { minimum: 5 }

  # Twitter raw-data
  serialize :twitter_raw_data

  def self.find_from_omniauth(omniauth_data)
  User.where(provider: omniauth_data["provider"],
             uid:      omniauth_data["uid"]).first
  end

  def self.create_from_omniauth(omniauth_data)
  full_name = omniauth_data["info"]["name"].split
  User.create(uid:                      omniauth_data["uid"],
              provider:                 omniauth_data["provider"],
              first_name:               full_name[0],
              last_name:                full_name[1],
              twitter_consumer_token:   omniauth_data["credentials"]["token"],
              twitter_consumer_secret:  omniauth_data["credentials"]["secret"],
              twitter_raw_data:         omniauth_data,
              password:                 SecureRandom.hex(16)
              )
            end

  private

  def from_omniauth?
    uid.present? && provider.present?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  def index
    @beans = Bean.first(3)
    @shops = Shop.first(3)
    @recipes = Recipe.first(3)
  end
end

app/helpers/bean_likes_helper.rb
module BeanLikesHelper
end

app/helpers/bean_shops_helper.rb
module BeanShopsHelper
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<header class="main_h">
  <div class="row">
    <a class="logo">JavaHub</a>
    <div class="mobile-toggle">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <nav>
      <ul>
        <li class="hvr-overline-from-right"><%= link_to "Home", root_path%></li>
        <li class="hvr-overline-from-right"><%= link_to "Bean", beans_path %></li>
        <li class="hvr-overline-from-right"><%= link_to "Shop", shops_path %></li>
        <li class="hvr-overline-from-right"><%= link_to "Recipe", recipes_path %></li>
        <% if user_signed_in? %>
          <li class="hvr-overline-from-right"><%= link_to "Profile", user_path(current_user) %></li>
          <li class="hvr-overline-from-right"><%= link_to "Logout", sessions_path, method: :delete,
                 data: {confirm: "are you sure you want to log out?"}%></li>

          <li class="avatar hvr-overline-from-right"><%= link_to image_tag(current_user.avatar_url(:xxsmall).to_s), user_path(current_user) %><li>
        <% else %>
          <li class="navbar-right hvr-overline-from-right"><%= link_to "Login", new_session_path %></li>
          <li class="navbar-right hvr-overline-from-right"><%= link_to fa_icon("twitter", base: "square-o", class: "fa-2x"), sign_in_with_twitter_path%></li>
          <li class="navbar-right hvr-overline-from-right"><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div> <!-- / row -->
</header>

<!-- header-container -->
  <div class="header-container">
    <div class="video-container">
      <video class="video" autoplay loop muted>
        <source src="coffee.mp4" type="video/mp4"/>
        <source src="coffee.ogg" type="video/ogg"/>
        Your browser does not support the video tag.
      </video>
    </div> <!-- end of video-container -->
  </div>
  <!-- end of header-container -->

<!-- search -->

<!-- end of search -->

  <!-- popular shops/recipes -->
<div class="container" id="bean-home">
  <div class="container">
    <h2 class="no-span">These are the beans you are looking for</h2>
    <div class="row">
      <% @beans.each do |f| %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="circle hvr-grow"><%= link_to image_tag(f.beanimg_url(:thumb)), bean_path(f) %><%= f.name %></div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container" id="bean-home">
  <div class="container">
    <h2 class="no-span">Places to bean</h2>
    <div class="row">
      <% @shops.each do |f| %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="circle hvr-grow"><%= link_to image_tag(f.cafeimg_url(:thumb)), shop_path(f) %><%= f.name %></div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container" id="recipe-home">
  <div class="container">
    <div class="row">
      <h2 class="no-span">Trending drinks</h2>
      <% @recipes.each do |f| %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="circle hvr-grow"><%= link_to image_tag(f.recipeimg_url(:thumb)), recipe_path(f) %><%= f.name %></div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<!-- end of popular shops/recipes -->

<!-- Service -->
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Our Services</h2>
                <hr class="hr-index">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa fa-coffee wow bounceIn text-primary"></i>
                    <h3>Beans</h3>
                    <p class="text-muted">Help you find your next favourite Beans.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-map-o  wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Cafes</h3>
                    <p class="text-muted">Search amazing cafes near you.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-book wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Recipe</h3>
                    <p class="text-muted">Write and save your recipe. See what other people are making.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-pie-chart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Recommendation</h3>
                    <p class="text-muted">Recomendations based on your taste!</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- service end -->
<!-- big pictures -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="hr-index">
                <p>Have any suggestions! Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>(604) 559-2633</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">dohoonk.smg@gmail.com</a></p>
            </div>
        </div>
    </div>
</section>

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="js/jquery.easing.min.js"></script>
<script src="js/jquery.fittext.js"></script>
<script src="js/wow.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="js/creative.js"></script>
<!-- end of big picture -->

<!-- Footer-cotainer -->

  <footer>
    <div class="container">
      <p>Copyright Tony Kim 2016</p>
    </div>
  </footer>

<!-- End of footer-container -->